### ISSUE TITLE
Add compatibility with Non-Renewing Subscriptions

### ISSUE THREAD

**Issue by ghost** [MugunthKumar/MKStoreKit#143]
I am being forced by Apple to change my In-App purchase auto-renewable subscriptions to non-renewing subscriptions. A few quick fixes (Issue #76 ) allowed me to verify that a non-renewing subscription has been purchased, and even detects the expiration date by comparing date of purchase and length of subscription. However, since users can purchase multiple non-renewing subscriptions even while currently subscribed, there needs to be a better way of tracking the "total subscription length" when this happens as the current method doesn't work.

Currently, only the latest receipt is used to check for expiration, and doesn't take into effect prior receipts that are still valid.

Hoping this could be a quick fix as I just need to fix this before re-submitting my app.
Thanks!

**Comment by lorenzoPrimi** [comment]
How did you solve this?
I can't find any help on how to use a non renewing subscription with MKStoreKit. 
Did you changed to consumable and store the date on a server? Would it work?
