### ISSUE TITLE
[Feature] automatic Activity Indicator

### ISSUE THREAD

**Issue by David-Drechsel-ewerk** [MugunthKumar/MKStoreKit#195]
It would be nice to add an optional automatic 'purchase in progress' indicator. An overlay or something that shows the user that the app 'does something'.

**Comment by Sam-Spencer** [comment]
Why not just update the interface on your own? Have a `startLoadAnimations` and a `stopLoadAnimations` method, or even better: `shouldAnimateLoadElements:(BOOL)animate`. Call the method when appropriate (e.g. just before starting a purchase, and then again when it finishes / fails).

Every app has a different interface, so there's no *one solution fits all* to this.

**Comment by MugunthKumar** [comment]
I don't think I'll implement this.
You can easily do this by starting your animation before you call `startProductRequest` and stop it after getting a kMKStoreKitProductPurchasedNotification or kMKStoreKitProductPurchaseDeferredNotification or kMKStoreKitProductPurchaseFailedNotification.
