### ISSUE TITLE
Podspec?

### ISSUE THREAD

**Issue by cytryn** [MugunthKumar/MKStoreKit#197]
You updated this version but forgot the podspec I guess...

Can you update?

**Comment by MugunthKumar** [comment]
I've created and pushed a tag 6.0b1.
You should ask the Cocoapods guys to create a podspec on their end.

**Comment by siberianisaev** [comment]
```We don't create pod specifications for individual libraries. It is up to their maintainers or third parties to create and maintain specifications.```
