### ISSUE TITLE
Import to swift code

### ISSUE THREAD

**Issue by siberianisaev** [MugunthKumar/MKStoreKit#199]
After import MKStoreKit.h to (ProjectName)Bridging-Header.h, pre-compiler error received

```
MKStoreKit is ARC only. Either turn on ARC for the project or use -fobjc-arc flag
```

'objc_arc' feature isn't defined in swift

**Comment by Sam-Spencer** [comment]
Great fix! +1

**Comment by MugunthKumar** [comment]
Fixed and closed

**Comment by siberianisaev** [comment]
### Update ###

solution 1598038fa15e85ade0a07b37f51b22c658d96962 is only applies if there is no files with '-fno-objc-arc' flag in

```
Target -> Build Phases -> Compile Sources
```

Thus it would be better to replace an #error on #warning.
