### ISSUE TITLE
Incorrect Expiry Dates

### ISSUE THREAD

**Issue by jspavlick** [MugunthKumar/MKStoreKit#212]
Correct me if I'm wrong, but `return [NSDate dateWithTimeIntervalSince1970:[expiresDateMs doubleValue]];` is incorrect. The `[expiresDatesMs doubleValue]` should be divided by 1000 to obtain the number of seconds since 1970, not the number of milliseconds.

**Comment by Sam-Spencer** [comment]
I think you're right here. Working on this recently and noticed that the code for checking expirations was a little fishy. More testing is needed to confirm, but looks like this is the problem.

**Comment by jspavlick** [comment]
I was getting expiry dates in the year 47,007 or something similar. Dividing by 1000 gave me expected results.

**Comment by MugunthKumar** [comment]
You are right. This is fixed in one of the PR I merged.
