### ISSUE TITLE
Consumable that bundles multiple ConsumableIds? Is this possible?

### ISSUE THREAD

**Issue by brunophilipe** [MugunthKumar/MKStoreKit#214]
My game has two "currencies", and I have individual in-app purchases for each of them.
However, one of the in-app purchases I want to implement would bundle a quantity of each currency in a single productId. Is this supported by MKStoreKit by default or do I need to make modifications?

**Comment by MugunthKumar** [comment]
It is.
You can list all product ids in the plist and set the ConsumableID on each one of them to the corresponding virutal currency name.
