### ISSUE TITLE
Restore purchase always success 

### ISSUE THREAD

**Issue by terflogag** [MugunthKumar/MKStoreKit#256]
Hello,

I'm trying to make a simple IAP for delete all the Ad of my app.
When I buy IAP it work, but when I try to restaure purchase with clear sandbox account (which have never buy the IAP), it work. 

So, the restorePurchases() always work, even if the user don't have buy the IAP previously.

There is my code : 
When user select restore button I perform this method : 

```
    func restaureIAP() {
        PKNotification.toast("Chargement en cours...")
        MKStoreKit.sharedKit().restorePurchases()
    }
```

I have also add observer : 

```
// Product restaure
        NSNotificationCenter.defaultCenter().addObserverForName(kMKStoreKitRestoredPurchasesNotification,
            object: nil, queue: NSOperationQueue.mainQueue()) { (note) -> Void in
                PKNotification.success("Restauré !")
                print ("Succes restaure: \(note.object)")

                NSUserDefaults.standardUserDefaults().setBool(true, forKey: "isPurchase")
        }

        NSNotificationCenter.defaultCenter().addObserverForName(kMKStoreKitRestoringPurchasesFailedNotification,
            object: nil, queue: NSOperationQueue.mainQueue()) { (note) -> Void in
                PKNotification.failed("Erreur")
                print ("Failed restaure: \(note.object)")
        }
```

This app is available on the AppStore, and have the same problem : buy IAP work but restore purchase are always successful.

Have you any ideas ?

Thank's for your responses and for this awesome API.

**Comment by giifty** [comment]
I'm getting the same error...

**Comment by marcusgbrown** [comment]
isPurchased always will return YES after a purchase is made on the device until you delete the app, regardless of your account in the app. Instead you should check expiryDateForProduct:yourProductIdentifier which returns an expiration date for the product and compare expiration date to current date to check if a user has purchased the product and enable/disable accordingly.

**Comment by terflogag** [comment]
In my case, it's non consumable IAP. And expiryDateForProduct:yourProductIdentifier return "1970-01-01 00:00:00 +0000". 
Have you any exemple ?

**Comment by protspace** [comment]
1970-01-01 00:00:00 +0000 can appear if you first launched the app and Test user is not logged ti App Store. Try to log in in Settings first.

**Comment by woaibujian** [comment]
same issue here.
